"""delete record_name

Revision ID: 0e9330216555
Revises: 4f5ec4b9c3ac
Create Date: 2024-09-16 17:34:09.818497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9330216555'
down_revision: Union[str, None] = '4f5ec4b9c3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('records_record_name_key', 'records', type_='unique')
    op.drop_column('records', 'record_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('record_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('records_record_name_key', 'records', ['record_name'])
    # ### end Alembic commands ###
