"""update Target model

Revision ID: 58546056bac0
Revises: b738d625ecdf
Create Date: 2024-09-16 16:21:19.945877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58546056bac0'
down_revision: Union[str, None] = 'b738d625ecdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('record_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'targets', 'records', ['record_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'targets', type_='foreignkey')
    op.drop_column('targets', 'record_id')
    # ### end Alembic commands ###
