"""Added a new targets table

Revision ID: 6934f545b770
Revises: 896426ce75c8
Create Date: 2024-09-06 17:09:57.584442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6934f545b770'
down_revision: Union[str, None] = '896426ce75c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.alter_column('targets', 'value',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=4, scale=2),
               existing_nullable=True)
    op.create_foreign_key(None, 'targets', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'targets', type_='foreignkey')
    op.alter_column('targets', 'value',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('targets', 'owner_id')
    # ### end Alembic commands ###
