"""add added_at file in Record model

Revision ID: 75862c081f81
Revises: e11c1bfedeea
Create Date: 2024-09-19 14:05:17.454722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75862c081f81'
down_revision: Union[str, None] = 'e11c1bfedeea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('added_at', sa.Date(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'added_at')
    # ### end Alembic commands ###
