"""deleted song table

Revision ID: 896426ce75c8
Revises: 21bf99d63857
Create Date: 2024-09-05 16:57:16.597357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '896426ce75c8'
down_revision: Union[str, None] = '21bf99d63857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_songs_author_id', table_name='songs')
    op.drop_table('songs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('song_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('publish_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='songs_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='songs_pkey'),
    sa.UniqueConstraint('song_name', name='songs_song_name_key')
    )
    op.create_index('ix_songs_author_id', 'songs', ['author_id'], unique=False)
    # ### end Alembic commands ###
