"""add record table

Revision ID: b738d625ecdf
Revises: dc2fea862b5f
Create Date: 2024-09-16 16:12:37.302955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b738d625ecdf'
down_revision: Union[str, None] = 'dc2fea862b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('targets_dict', sa.JSON(), nullable=True))
    op.add_column('records', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'records', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_column('records', 'owner_id')
    op.drop_column('records', 'targets_dict')
    # ### end Alembic commands ###
