"""update Tartget model

Revision ID: caf164ad8804
Revises: cfa3b6f7d09d
Create Date: 2024-09-21 12:42:07.233625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf164ad8804'
down_revision: Union[str, None] = 'cfa3b6f7d09d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('targets', 'value',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('targets', 'value',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('records', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
