"""add new field record_name 2

Revision ID: e11c1bfedeea
Revises: 0e9330216555
Create Date: 2024-09-16 17:35:23.949115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e11c1bfedeea'
down_revision: Union[str, None] = '0e9330216555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('record_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'record_name')
    # ### end Alembic commands ###
